#!/bin/bash

echo "🚀 Return Address - Vercel Deployment Script"
echo "=============================================="
echo ""
echo "This script will help you deploy to Vercel."
echo ""
echo "Option 1: Use Vercel Web Interface (Recommended)"
echo "  1. Go to: https://vercel.com/new"
echo "  2. Import: Dewars30/return-address"
echo "  3. Configure environment variables"
echo "  4. Deploy"
echo ""
echo "Option 2: Use Vercel CLI"
echo "  Run: vercel"
echo ""
echo "Press any key to continue with CLI deployment..."
read -n 1

echo ""
echo "Linking project to Vercel..."
vercel link

echo ""
echo "Adding environment variables..."
echo "You'll need to add these manually or via Vercel Dashboard:"
echo "  - DATABASE_URL"
echo "  - NEXT_PUBLIC_APP_URL=https://returnaddress.io"
echo "  - CLERK_SECRET_KEY"
echo "  - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
echo "  - STRIPE_SECRET_KEY"
echo "  - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
echo "  - STRIPE_WEBHOOK_SECRET"
echo "  - OPENAI_API_KEY"
echo "  - S3_ENDPOINT"
echo "  - S3_ACCESS_KEY_ID"
echo "  - S3_SECRET_ACCESS_KEY"
echo "  - S3_BUCKET_NAME"
echo "  - S3_REGION"
echo "  - SUPABASE_URL"
echo "  - SUPABASE_SERVICE_ROLE_KEY"
echo "  - ADMIN_EMAILS"
echo "  - PLATFORM_FEE_BPS"
echo ""
echo "Deploying to production..."
vercel --prod

echo ""
echo "✅ Deployment complete!"
echo "Next: Configure domain at https://vercel.com/dashboard"
